// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AxHeader: typeof import('./../components/ax-header/index.vue')['default']
    Header: typeof import('./../components/header/index.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    Layout111: typeof import('./../components/Layout111.vue')['default']
    Logo: typeof import('./../components/logo/index.vue')['default']
    Main: typeof import('./../components/Main.vue')['default']
    MainLayout: typeof import('./../components/MainLayout.vue')['default']
    Menu: typeof import('./../components/menu/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    Navbar: typeof import('./../components/navbar/index.vue')['default']
    NavbarActions: typeof import('./../components/navbar/components/navbarActions.vue')['default']
    NavbarAvatar: typeof import('./../components/navbar/components/navbarAvatar.vue')['default']
    NavbarBreadcrumb: typeof import('./../components/navbar/components/navbarBreadcrumb.vue')['default']
    NavbarFoldIcon: typeof import('./../components/navbar/components/navbarFoldIcon.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEl: typeof import('naive-ui')['NEl']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    Order: typeof import('./../components/chart/order.vue')['default']
    OrderChart: typeof import('./../components/chart/orderChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollerMenu: typeof import('../components/menu/index.vue')['default']
    Sidebar: typeof import('./../components/sidebar/index.vue')['default']
    TheCounter: typeof import('./../components/TheCounter.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    TheInput: typeof import('./../components/TheInput.vue')['default']
    VueEcharts: typeof import('./../components/vue-echarts/index.vue')['default']
  }
}
