// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../views/error/404.vue')['default']
    AlbumItem: typeof import('./../views/dashboard/components/albumItem.vue')['default']
    AxHeader: typeof import('./../components/ax-header/index.vue')['default']
    ChinaMapChart: typeof import('./../views/dashboard/components/chart/china-map-chart/index.vue')['default']
    ChinaMapItem: typeof import('./../views/dashboard/components/chinaMapItem.vue')['default']
    DeformationChart: typeof import('./../views/dashboard/components/chart/deformation-chart/index.vue')['default']
    DeformationChartItem: typeof import('./../views/dashboard/components/deformationChartItem.vue')['default']
    Dep: typeof import('./../views/dep/index.vue')['default']
    FlyBox: typeof import('./../components/flyBox/index.vue')['default']
    Github: typeof import('./../views/github.vue')['default']
    GradientText: typeof import('./../components/gradient-text/index.vue')['default']
    HeaderSetting: typeof import('./../components/setting/components/header-setting/index.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LayoutAnimationSetting: typeof import('./../components/setting/components/layout-animation-setting/index.vue')['default']
    LayoutMain: typeof import('./../components/LayoutMain.vue')['default']
    Login: typeof import('./../views/login/index.vue')['default']
    Logo: typeof import('./../components/logo/index.vue')['default']
    MapleItem: typeof import('./../views/dashboard/components/mapleItem.vue')['default']
    Menu: typeof import('./../components/menu/index.vue')['default']
    MenuSetting: typeof import('./../components/setting/components/menu-setting/index.vue')['default']
    Navbar: typeof import('./../components/navbar/index.vue')['default']
    NavbarActions: typeof import('./../components/navbar/components/navbarActions.vue')['default']
    NavbarAvatar: typeof import('./../components/navbar/components/navbarAvatar.vue')['default']
    NavbarBreadcrumb: typeof import('./../components/navbar/components/navbarBreadcrumb.vue')['default']
    NavbarFoldIcon: typeof import('./../components/navbar/components/navbarFoldIcon.vue')['default']
    NavbarMusicIcon: typeof import('./../components/navbar/components/navbarMusicIcon.vue')['default']
    NavbarNotification: typeof import('./../components/navbar/components/navbarNotification.vue')['default']
    NavbarSetting: typeof import('./../components/setting/components/navbar-setting/index.vue')['default']
    Redirect: typeof import('./../views/redirect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleContainer: typeof import('./../components/scale-container/index.vue')['default']
    Search: typeof import('./../components/search/index.vue')['default']
    Setting: typeof import('./../components/setting/index.vue')['default']
    Tabbar: typeof import('./../components/tabbar/index.vue')['default']
    TabbarSetting: typeof import('./../components/setting/components/tabbar-setting/index.vue')['default']
    TheInput: typeof import('./../components/TheInput.vue')['default']
    ThemeColorSetting: typeof import('./../components/setting/components/theme-color-setting/index.vue')['default']
    ThemeSetting: typeof import('./../components/setting/components/theme-setting/index.vue')['default']
    ThemeSettingAnother: typeof import('./../components/setting/components/theme-setting/theme-setting-another.vue')['default']
    VueEcharts: typeof import('./../components/vue-echarts/index.vue')['default']
    WatchMarkSetting: typeof import('./../components/setting/components/watchMarkSetting/index.vue')['default']
    Workbench: typeof import('./../views/dashboard/workbench.vue')['default']
  }
}
